#!/usr/bin/env python3
import argparse
from pathlib import Path


def c_ident(path: str, index: int) -> str:
    safe = ''.join(ch if ch.isalnum() else '_' for ch in path)
    return f'asset_{index}_{safe}'


def bytes_to_c(data: bytes) -> str:
    if not data:
        return '0'
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append('  ' + ', '.join(f'0x{byte:02x}' for byte in chunk))
    return ',\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description='Pack static assets for Mongoose')
    parser.add_argument('input_dir', type=Path)
    parser.add_argument('output_c', type=Path)
    parser.add_argument('--mount', default='/web')
    args = parser.parse_args()

    input_dir = args.input_dir.resolve()
    if not input_dir.is_dir():
        raise SystemExit(f'{input_dir} is not a directory')

    files = sorted(path for path in input_dir.rglob('*') if path.is_file())
    args.output_c.parent.mkdir(parents=True, exist_ok=True)

    mount = '/' + args.mount.strip('/')
    chunks = [
        '/* Generated by tools/pack_assets.py. Do not edit by hand. */',
        '#include "mongoose.h"',
        ''
    ]
    entries = []

    for index, path in enumerate(files):
        rel = path.relative_to(input_dir).as_posix()
        name = c_ident(rel, index)
        data = path.read_bytes()
        chunks.append(f'static const unsigned char {name}[] = {{')
        chunks.append(bytes_to_c(data))
        chunks.append('};')
        chunks.append('')
        entries.append((f'{mount}/{rel}', name, len(data)))

    chunks.append('const struct mg_mem_file mg_packed_files[] = {')
    for asset_path, name, size in entries:
        chunks.append(f'  {{"{asset_path}", {name}, {size}, 0}},')
    chunks.append('  {NULL, NULL, 0, 0}')
    chunks.append('};')
    chunks.append('')

    args.output_c.write_text('\n'.join(chunks), encoding='utf-8')
    print(f'Packed {len(entries)} assets into {args.output_c}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
